"""add task completion history"""

import sqlalchemy as sa
from alembic import op

revision = "1a25ffb0f172"
down_revision = "062afbf77b76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_completions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_task_completions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_completions")),
    )
    with op.batch_alter_table("task_completions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_completions_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_completions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_completions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_completions_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_completions_task_id"))

    op.drop_table("task_completions")
    # ### end Alembic commands ###
